/*
 * Proyecto: LED Layout Editor (XML Tool for ANC LiveSync-Compatible Files) 
 * Autor: Brandon Iván Covarrubias Minez
 * Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)
 * https://creativecommons.org/licenses/by-nc/4.0/
 */

package SlaveForm;

import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JSpinner;
import javax.swing.JTextField;

public class V_SlaveForm extends javax.swing.JDialog {

    /**
     * Creates new form V_SlaveForm
     */
    public V_SlaveForm() {
        super(new Frame(), true);
        initComponents();
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public JTextField getTxtNameSlave() {
        return txtNameSlave;
    }

    public JTextField getTxtNameBackup() {
        return txtNameBackup;
    }

    public JTextField getTxtAddress() {
        return txtAddress;
    }

    public JCheckBox getCkbBackup() {
        return ckbBackup;
    }

    public JCheckBox getCkbOffset() {
        return ckbOffset;
    }

    public JSpinner getSprOffset() {
        return sprOffset;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNameSlave = new javax.swing.JTextField();
        ckbOffset = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNameBackup = new javax.swing.JTextField();
        sprOffset = new javax.swing.JSpinner();
        ckbBackup = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Slave"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Slave Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, -1));
        jPanel1.add(txtNameSlave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 220, -1));

        ckbOffset.setBackground(new java.awt.Color(255, 255, 255));
        ckbOffset.setSelected(true);
        ckbOffset.setText("Offset");
        ckbOffset.setNextFocusableComponent(sprOffset);
        jPanel1.add(ckbOffset, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Address:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        btnSave.setText("Save");
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 130, -1));

        btnCancel.setText("Cancel");
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Backup Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, -1));

        txtNameBackup.setBackground(new java.awt.Color(238, 238, 238));
        txtNameBackup.setEnabled(false);
        jPanel1.add(txtNameBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 220, -1));

        sprOffset.setModel(new javax.swing.SpinnerNumberModel(1920, 0, null, 1920));
        jPanel1.add(sprOffset, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 220, -1));

        ckbBackup.setBackground(new java.awt.Color(255, 255, 255));
        ckbBackup.setText("BackUp");
        ckbBackup.setNextFocusableComponent(txtNameBackup);
        jPanel1.add(ckbBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Offset X:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, -1));

        txtAddress.setText("localhost");
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 220, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 180));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox ckbBackup;
    private javax.swing.JCheckBox ckbOffset;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner sprOffset;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtNameBackup;
    private javax.swing.JTextField txtNameSlave;
    // End of variables declaration//GEN-END:variables
}
