/*
 * Proyecto: LED Layout Editor (XML Tool for ANC LiveSync-Compatible Files) 
 * Autor: Brandon Iván Covarrubias Minez
 * Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)
 * https://creativecommons.org/licenses/by-nc/4.0/
 */

package HdmiOutput;

import Heirs.pnlZoomeable;
import Screen.V_Screen;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Stroke;

public class V_HdmiOutput extends pnlZoomeable{

    public V_HdmiOutput() {
        initComponents();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        //Rejilla punteada cada 1920 horizontal y 1080 vertical
        Graphics2D g2d = (Graphics2D) g.create();
        g2d.setColor(Color.GRAY);

        float[] pattern = {10, 10};
        Stroke dashed = new BasicStroke(1, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 0, pattern, 0);
        g2d.setStroke(dashed);

        int trueWidth = getTrueWidth();    // sin zoom
        int trueHeight = getTrueHeight();  // sin zoom

        int visibleWidth = getWidth();     // con zoom
        int visibleHeight = getHeight();   // con zoom

        for (int x = 1920; x < trueWidth; x += 1920) {
            int xZoomed = applyZoom(x);  // nuevo método
            if (xZoomed >= 0 && xZoomed <= visibleWidth) {
                g2d.drawLine(xZoomed, 0, xZoomed, visibleHeight);
            }
        }

        for (int y = 1080; y < trueHeight; y += 1080) {
            int yZoomed = applyZoom(y);
            if (yZoomed >= 0 && yZoomed <= visibleHeight) {
                g2d.drawLine(0, yZoomed, visibleWidth, yZoomed);
            }
        }

        g2d.dispose();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    void addScreen(V_HdmiOutput View, V_Screen view) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}