/*
 * Proyecto: LED Layout Editor (XML Tool for ANC LiveSync-Compatible Files) 
 * Autor: Brandon Iván Covarrubias Minez
 * Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)
 * https://creativecommons.org/licenses/by-nc/4.0/
 */

package Section;

import java.awt.Color;
import javax.swing.*;

import Heirs.pnlZoomeable;
import java.awt.BorderLayout;

public class V_Section extends pnlZoomeable{
    private final JPanel pnlMovement;
    private final JPanel pnlMargin;
    private final JLabel lblName;
    
    public V_Section() {
        initComponents();

        pnlMovement= new JPanel();
        pnlMargin= new JPanel();
        lblName= new JLabel();

        lblName.setHorizontalAlignment(JLabel.CENTER);
        lblName.setVerticalAlignment(JLabel.CENTER);
        lblName.setForeground(Color.WHITE);
        
        //pnlMovement.setBackground(new Color(61, 111, 86));
        //pnlMargin.setBackground(new Color(190, 31, 51));
        
        pnlMovement.setVisible(true);
        pnlMargin.setVisible(true);
        pnlMovement.setLayout(new BorderLayout());
        
        actTrueBounds();

        
        pnlMovement.add(lblName);
        this.add(pnlMovement);
        this.add(pnlMargin);
        
        
        repaint();
    }
    
    
    
    @Override
    public void actTrueBounds(){
        super.actTrueBounds();
        pnlMovement.setBounds(M_Section.INT_MARGIN, M_Section.INT_MARGIN, this.getWidth()-M_Section.INT_MARGIN*2, this.getHeight()-M_Section.INT_MARGIN*2);
        pnlMargin.setBounds(0, 0, this.getWidth(), this.getHeight());
        
        lblName.setSize(pnlMovement.getSize());
    }

    JPanel getPnlMovement(){
        return pnlMovement;
    }
    
    JPanel getPnlMargin(){
        return pnlMargin;
    }

    public JLabel getLblName() {
        return lblName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
